import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'

import Footer from '@/components/footer'
import Navbar from '@/components/navbar'

import './globals.css'

const poppins = Poppins({
  variable: '--font-poppins',
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  style: ['normal', 'italic'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={`${poppins.variable} flex min-h-screen flex-col justify-between antialiased`}
      >
        <Navbar />
        <main className='flex flex-1 py-6'>{children}</main>
        <Footer />
      </body>
    </html>
  )
}
