/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/admin/categories': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * create category
     * @description create category
     */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      /** @description request body */
      requestBody: {
        content: {
          'application/json': components['schemas']['dto.CreateCategoryRequest']
        }
      }
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/admin/categories/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /**
     * delete category
     * @description delete category
     */
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description category id */
          id: number
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
      }
    }
    options?: never
    head?: never
    /**
     * update category
     * @description update category
     */
    patch: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description category id */
          id: number
        }
        cookie?: never
      }
      /** @description request body (don't need to include id) */
      requestBody: {
        content: {
          'application/json': components['schemas']['dto.UpdateCategoryRequest']
        }
      }
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
      }
    }
    trace?: never
  }
  '/api/v1/auth/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Login
     * @description Login
     */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      /** @description request request */
      requestBody: {
        content: {
          'application/json': components['schemas']['dto.LoginRequest']
        }
      }
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpResponse-dto_LoginResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/logout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Logout
     * @description Logout
     */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/refresh-token': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Refresh Token
     * @description Refresh Token
     */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      /** @description request request */
      requestBody: {
        content: {
          'application/json': components['schemas']['dto.RefreshTokenRequest']
        }
      }
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpResponse-dto_TokenResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/register': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Register
     * @description Register
     */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      /** @description request request */
      requestBody: {
        content: {
          'application/json': components['schemas']['dto.RegisterRequest']
        }
      }
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpResponse-dto_RegisterResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/categories': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * list category
     * @description list category
     */
    get: {
      parameters: {
        query?: {
          /** @description Page number for pagination (default: 1) */
          page?: number
          /** @description Number of records per page (default: 20) */
          pageSize?: number
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpResponse-PaginationResponse[dto_CategoryResponse]']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/customer/quotations/{id}/accept': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /**
     * accept preview photo
     * @description accept preview photo
     */
    patch: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description quotaion id */
          id: number
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
      }
    }
    trace?: never
  }
  '/api/v1/customer/quotations/{id}/cancel': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /**
     * cancelled quotation
     * @description cancelled quotaion
     */
    patch: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description quotaion id */
          id: number
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
      }
    }
    trace?: never
  }
  '/api/v1/customer/quotations/{id}/confirm': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /**
     * confirm quotation
     * @description confirm quotaion
     */
    patch: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description quotaion id */
          id: number
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
      }
    }
    trace?: never
  }
  '/api/v1/customer/quotations/{id}/review': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Create a review
     * @description Create a review for a quotation.
     */
    post: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description Quotation ID */
          id: string
        }
        cookie?: never
      }
      /** @description Review details */
      requestBody: {
        content: {
          'application/json': components['schemas']['dto.CreateReviewRequest']
        }
      }
      responses: {
        /** @description Review created successfully */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/customers/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get customer public profile
     * @description Get customer public profile
     */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description customer's userId */
          id: number
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpResponse-dto_CustomerPublicResponse']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get me
     * @description Get me
     */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpResponse-dto_UserResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /**
     * Update me
     * @description Update user's profile
     */
    patch: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      /** @description request request */
      requestBody: {
        content: {
          'application/json': components['schemas']['dto.UserUpdateRequest']
        }
      }
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpResponse-dto_UserResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
      }
    }
    trace?: never
  }
  '/api/v1/messages': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * list all chats
     * @description list all chats for each individual user
     */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpListResponse-dto_ChatResponse']
          }
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/messages/ws': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * connect to websocket
     * @description Establish a WebSocket connection for real-time communication.
     *     The message from a server will be in a format of "[EVENT] [MESSAGE]" which [EVENT] can be "ERROR" or "MESSAGE".
     *     If [EVENT] is error, [MESSAGE] will be a string of error message ,otherwise it will be a dto.RealTimeMessageResponse
     */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Switching Protocols */
        101: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/objects': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Upload image
     * @description receive formData body, path (string, folder path, don't include ".." or prefix with "/") and file
     */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      /** @description folder enum (PACKAGE, VERIFY_CITIZENCARD, PROFILE_IMAGE) */
      requestBody?: {
        content: {
          'application/x-www-form-urlencoded': string
        }
      }
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpResponse-dto_ObjectUploadResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
      }
    }
    /**
     * Delete image
     * @description Delete image
     */
    delete: {
      parameters: {
        query: {
          /** @description image url */
          URL: string
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/packages': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get all packages
     * @description Show all available packages with pagination
     */
    get: {
      parameters: {
        query?: {
          /** @description Filter by package name */
          name?: string
          /** @description Page number */
          page?: number
          /** @description Page size */
          pageSize?: number
          /** @description Minimum price */
          minPrice?: number
          /** @description Maximum price */
          maxPrice?: number
          /** @description Photographer ID */
          photographerId?: number
          /** @description list of categoryIDs separate by comma ex: 1,2 */
          categoryIds?: string
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.PaginationResponse-dto_PackageResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/packages/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * get package by id
     * @description Show package detail
     */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description package id */
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpResponse-dto_PackageResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/packages/{packageID}/reviews': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * get package reviews by package id
     * @description Show reviews of a package
     */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description package id */
          packageID: number
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpListResponse-dto_ReviewResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/photographer/citizen-card': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Citizen Card
     * @description Get Photographer Citizen Card
     */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpResponse-dto_CitizenCardResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/photographer/citizen-card/reverify': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /**
     * Reverify Citizen Card
     * @description Reverify Photographer Citizen Card
     */
    patch: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      /** @description request request */
      requestBody: {
        content: {
          'application/json': components['schemas']['dto.ReVerifyCitizenCardRequest']
        }
      }
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpResponse-dto_CitizenCardResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
      }
    }
    trace?: never
  }
  '/api/v1/photographer/citizen-card/verify': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Verify Citizen Card
     * @description Verify Photographer Citizen Card
     */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      /** @description request request */
      requestBody: {
        content: {
          'application/json': components['schemas']['dto.VerifyCitizenCardRequest']
        }
      }
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpResponse-dto_CitizenCardResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/photographer/media': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Create Media
     * @description Create media by photographer
     */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      /** @description Media details */
      requestBody: {
        content: {
          'application/json': components['schemas']['dto.CreateMediaRequest']
        }
      }
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/photographer/media/{mediaId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /**
     * Delete Media
     * @description Delete media
     */
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description media id */
          mediaId: string
        }
        cookie?: never
      }
      /** @description Media details */
      requestBody: {
        content: {
          'application/json': components['schemas']['dto.DeleteMediaRequest']
        }
      }
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
      }
    }
    options?: never
    head?: never
    /**
     * Update Media
     * @description Update media
     */
    patch: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      /** @description Media details */
      requestBody: {
        content: {
          'application/json': components['schemas']['dto.UpdateMediaRequest']
        }
      }
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
      }
    }
    trace?: never
  }
  '/api/v1/photographer/packages': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Photographer's packages
     * @description List Photographer's packages
     */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpListResponse-dto_PackageResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
      }
    }
    put?: never
    /**
     * Create Package
     * @description Create Package by photographer
     */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      /** @description Package details */
      requestBody: {
        content: {
          'application/json': components['schemas']['dto.CreatePackageRequest']
        }
      }
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/photographer/packages/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /**
     * Update package
     * @description Update package
     */
    patch: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description package id */
          id: number
        }
        cookie?: never
      }
      /** @description Package details */
      requestBody: {
        content: {
          'application/json': components['schemas']['dto.UpdatePackageRequest']
        }
      }
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
      }
    }
    trace?: never
  }
  '/api/v1/photographer/quotations': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Create a quotation
     * @description Creates a new quotation for a customer and package
     */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      /** @description Quotation details */
      requestBody: {
        content: {
          'application/json': components['schemas']['dto.CreateQuotationRequest']
        }
      }
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/photographer/quotations/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /**
     * Update a quotation
     * @description Updates an existing quotation
     */
    patch: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description Quotation ID */
          id: number
        }
        cookie?: never
      }
      /** @description Quotation update details */
      requestBody: {
        content: {
          'application/json': components['schemas']['dto.UpdateQuotationRequest']
        }
      }
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
      }
    }
    trace?: never
  }
  '/api/v1/photographer/quotations/{id}/preview': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * submit preview photo
     * @description submit preview photo and set status to submitted
     */
    post: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description quotaion id */
          id: number
        }
        cookie?: never
      }
      /** @description preview details */
      requestBody: {
        content: {
          'application/json': components['schemas']['dto.CreatePreviewPhotoRequest']
        }
      }
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/photographers': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get All Photographers
     * @description Retrieve a paginated list of photographers, optionally filtered by name.
     */
    get: {
      parameters: {
        query?: {
          /** @description Page number for pagination (default: 1) */
          page?: number
          /** @description Number of records per page (default: 5, max: 20) */
          pageSize?: number
          /** @description Filter by photographer's name (case-insensitive) */
          name?: string
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.PaginationResponse-dto_PhotographerResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/photographers/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * get photographer by id
     * @description get photographer by id
     */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description photographer id */
          id: number
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpResponse-dto_PhotographerResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/quotations': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * list quotations
     * @description list quotations
     */
    get: {
      parameters: {
        query?: {
          /** @description Page number */
          page?: number
          /** @description Page size */
          page_size?: number
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.PaginationResponse-QuotationResponse']
          }
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.PaginationResponse-QuotationResponse']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/quotations/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Quotation By ID
     * @description Get Quotation By ID
     */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description quotaion id */
          id: number
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpResponse-dto_GetQuotationResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/stripe/checkout/quotations/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Create Stripe Checkout Session
     * @description Generates a Stripe checkout session for a quotation
     */
    post: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description Quotation ID */
          id: number
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.CheckoutSessionResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['dto.HttpError']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    'dto.CategoryResponse': {
      description?: string
      id?: number
      name?: string
    }
    'dto.ChatResponse': {
      messages?: components['schemas']['dto.RealTimeMessageResponse'][]
      user?: components['schemas']['dto.PublicUserResponse']
    }
    'dto.CheckoutSessionResponse': {
      checkout_url?: string
    }
    'dto.CitizenCardResponse': {
      citizenId?: string
      expireDate?: string
      laserId?: string
      picture?: string
    }
    'dto.CreateCategoryRequest': {
      description: string
      name: string
    }
    'dto.CreateMediaRequest': {
      description?: string
      packageId: number
      pictureUrl: string
    }
    'dto.CreatePackageRequest': {
      categoryId?: number
      description?: string
      media: components['schemas']['dto.MediaPackageRequest'][]
      name: string
      price: number
    }
    'dto.CreatePreviewPhotoRequest': {
      link: string
      quotationId: number
    }
    'dto.CreateQuotationRequest': {
      customerId: number
      description?: string
      fromDate: string
      packageId: number
      price: number
      toDate: string
    }
    'dto.CreateReviewRequest': {
      comment?: string
      id: string
      rating: number
    }
    'dto.CustomerPublicResponse': {
      id?: number
      name?: string
      profilePictureUrl?: string
    }
    'dto.CustomerResponse': {
      email?: string
      id?: number
      name?: string
      phoneNumber?: string
      profilePictureUrl?: string
    }
    'dto.DeleteMediaRequest': {
      mediaID?: number
    }
    'dto.GetQuotationResponse': {
      customer?: components['schemas']['dto.UserResponse']
      description?: string
      fromDate?: string
      id?: number
      package?: components['schemas']['dto.PackageResponse']
      photographer?: components['schemas']['dto.PhotographerResponse']
      previews?: components['schemas']['dto.ListPreviewResponse'][]
      price?: number
      status?: components['schemas']['model.QuotationStatus']
      toDate?: string
    }
    'dto.HttpError': {
      error?: string
    }
    'dto.HttpListResponse-dto_ChatResponse': {
      result?: components['schemas']['dto.ChatResponse'][]
    }
    'dto.HttpListResponse-dto_PackageResponse': {
      result?: components['schemas']['dto.PackageResponse'][]
    }
    'dto.HttpListResponse-dto_ReviewResponse': {
      data: ReviewResponse[]

      result?: components['schemas']['dto.ReviewResponse'][]
    }
    'dto.HttpResponse-PaginationResponse[dto_CategoryResponse]': {
      result?: components['schemas']['dto.PaginationResponse-dto_CategoryResponse']
    }
    'dto.HttpResponse-dto_CitizenCardResponse': {
      result?: components['schemas']['dto.CitizenCardResponse']
    }
    'dto.HttpResponse-dto_CustomerPublicResponse': {
      result?: components['schemas']['dto.CustomerPublicResponse']
    }
    'dto.HttpResponse-dto_GetQuotationResponse': {
      result?: components['schemas']['dto.GetQuotationResponse']
    }
    'dto.HttpResponse-dto_LoginResponse': {
      result?: components['schemas']['dto.LoginResponse']
    }
    'dto.HttpResponse-dto_ObjectUploadResponse': {
      result?: components['schemas']['dto.ObjectUploadResponse']
    }
    'dto.HttpResponse-dto_PackageResponse': {
      result?: components['schemas']['dto.PackageResponse']
    }
    'dto.HttpResponse-dto_PhotographerResponse': {
      result?: components['schemas']['dto.PhotographerResponse']
    }
    'dto.HttpResponse-dto_RegisterResponse': {
      result?: components['schemas']['dto.RegisterResponse']
    }
    'dto.HttpResponse-dto_TokenResponse': {
      result?: components['schemas']['dto.TokenResponse']
    }
    'dto.HttpResponse-dto_UserResponse': {
      result?: components['schemas']['dto.UserResponse']
    }
    'dto.ListPreviewResponse': {
      id?: number
      link?: string
      quotationId?: number
    }
    'dto.LoginRequest': {
      idToken: string
      /** @description GOOGLE */
      provider: string
    }
    'dto.LoginResponse': {
      accessToken?: string
      exp?: number
      refreshToken?: string
      user?: components['schemas']['dto.UserResponse']
    }
    'dto.MediaPackageRequest': {
      description?: string
      pictureUrl: string
    }
    'dto.MediaResponse': {
      description?: string
      id?: number
      pictureUrl?: string
    }
    'dto.ObjectUploadResponse': {
      url?: string
    }
    'dto.PackageResponse': {
      category?: components['schemas']['dto.CategoryResponse']
      description?: string
      id?: number
      media?: components['schemas']['dto.MediaResponse'][]
      name?: string
      photographer?: components['schemas']['dto.PhotographerResponse']
      price?: number
      reviews?: components['schemas']['dto.ReviewResponse'][]
      tags?: components['schemas']['dto.TagResponse'][]
    }
    'dto.PaginationResponse-QuotationResponse': {
      data?: components['schemas']['dto.QuotationResponse'][]
      page?: number
      pageSize?: number
      totalPage?: number
    }
    'dto.PaginationResponse-dto_CategoryResponse': {
      data?: components['schemas']['dto.CategoryResponse'][]
      page?: number
      pageSize?: number
      totalPage?: number
    }
    'dto.PaginationResponse-dto_PackageResponse': {
      data?: components['schemas']['dto.PackageResponse'][]
      page?: number
      pageSize?: number
      totalPage?: number
    }
    'dto.PaginationResponse-dto_PhotographerResponse': {
      data?: components['schemas']['dto.PhotographerResponse'][]
      page?: number
      pageSize?: number
      totalPage?: number
    }
    'dto.PhotographerResponse': {
      activeStatus?: boolean
      email?: string
      id?: number
      isVerified?: boolean
      name?: string
      packages?: components['schemas']['dto.SmallPackageResponse'][]
      phoneNumber?: string
      profilePictureUrl?: string
    }
    'dto.PublicUserResponse': {
      email?: string
      id?: number
      name?: string
      phoneNumber?: string
      profilePictureUrl?: string
      role?: string
    }
    'dto.QuotationResponse': {
      customer?: components['schemas']['dto.UserResponse']
      description?: string
      fromDate?: string
      id?: number
      package?: components['schemas']['dto.PackageResponse']
      photographer?: components['schemas']['dto.PhotographerResponse']
      price?: number
      status?: string
      toDate?: string
    }
    'dto.ReVerifyCitizenCardRequest': {
      citizenId?: string
      expireDate?: string
      imageUrl?: string
      laserId?: string
    }
    'dto.RealTimeMessageResponse': {
      content?: string
      id?: number
      receiverId?: number
      sendedAt?: string
      senderId?: number
      type?: components['schemas']['model.MessageType']
    }
    'dto.RefreshTokenRequest': {
      refreshToken: string
    }
    'dto.RegisterRequest': {
      idToken: string
      /** @description GOOGLE */
      provider: string
      /** @description CUSTOMER, PHOTOGRAPHER, ADMIN */
      role: string
    }
    'dto.RegisterResponse': {
      accessToken?: string
      exp?: number
      refreshToken?: string
      user?: components['schemas']['dto.UserResponse']
    }
    'dto.ReviewResponse': {
      comment?: string
      customer?: components['schemas']['dto.CustomerResponse']
      id?: number
      rating?: number
    }
    'dto.SmallPackageResponse': {
      category?: components['schemas']['dto.CategoryResponse']
      description?: string
      id?: number
      name?: string
      price?: number
    }
    'dto.TagResponse': {
      id?: number
      name?: string
    }
    'dto.TokenResponse': {
      accessToken?: string
      exp?: number
      refreshToken?: string
    }
    'dto.UpdateCategoryRequest': {
      description?: string
      id: number
      name?: string
    }
    'dto.UpdateMediaRequest': {
      description?: string
      mediaID: number
      pictureUrl?: string
    }
    'dto.UpdatePackageRequest': {
      categoryId?: number
      description?: string
      id: number
      name?: string
      price?: number
    }
    'dto.UpdateQuotationRequest': {
      customerId: number
      description?: string
      fromDate: string
      packageId: number
      price: number
      quotationID: string
      toDate: string
    }
    'dto.UserResponse': {
      accountNo?: string
      bank?: string
      bankBranch?: string
      email?: string
      facebook?: string
      id?: number
      instagram?: string
      name?: string
      phoneNumber?: string
      profilePictureUrl?: string
      role?: components['schemas']['model.UserRole']
    }
    'dto.UserUpdateRequest': {
      accountNo?: string
      bank?: string
      bankBranch?: string
      facebook?: string
      instagram?: string
      name?: string
      phoneNumber?: string
      profilePictureUrl?: string
    }
    'dto.VerifyCitizenCardRequest': {
      citizenId: string
      expireDate: string
      imageUrl: string
      laserId: string
    }
    'model.MessageType': string
    'model.QuotationStatus': string
    'model.UserRole': string
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export type operations = Record<string, never>
